[build]
  command = "yarn run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Configure functions
[functions]
  node_bundler = "esbuild"

# Environment variables needed (set these in Netlify dashboard):
# - TURSO_DATABASE_URL
# - TURSO_AUTH_TOKEN
# - AUTH_SECRET
# - NEXTAUTH_SECRET
# - NEXTAUTH_URL

