[build]
  command = "yarn run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  # Set NODE_ENV to production for proper database selection
  NODE_ENV = "production"

# Configure functions
[functions]
  node_bundler = "esbuild"

# Redirect rules for better error handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables needed (set these in Netlify dashboard):
# Required:
# - TURSO_DATABASE_URL (your Turso database URL)
# - TURSO_AUTH_TOKEN (your Turso auth token)
# - AUTH_SECRET (generate with: openssl rand -base64 32)
# - NEXTAUTH_SECRET (same as AUTH_SECRET)
# - NEXTAUTH_URL (your Netlify site URL, e.g., https://your-site.netlify.app)
# - NODE_ENV=production

